RegisterCommand('colecoes', function()
    NUI.Open('collections')
end, false)

RegisterCommand('badges', function()
    NUI.Open('badges')
end, false)

-- RegisterCommand('dnc_debug', function()
--     print('========== DN COLLECTIONS DEBUG ==========')
--     print('ClientState.Ready:', ClientState.Ready)
--     print('NUI.Ready:', NUI.Ready)
--     print('NUI.Focus:', NUI.Focus)
--     print('NUI.Queue size:', #NUI.Queue)
--     print('Trade.PendingRequest:', json.encode(Trade.PendingRequest or {}))
--     print('Trade.ActiveTrade:', json.encode(Trade.ActiveTrade or {}))
--     print('Objects.Held:', Objects.Held or 'none')
--     print('Cache.Catalog items:', Utils.TableCount(ClientState.Cache.Catalog or {}))
--     print('Cache.Items:', Utils.TableCount(ClientState.Cache.Items or {}))
--     print('=========================================')
-- end, false)

RegisterCommand('col', function()
    NUI.Open('collections')
end, false)